// Code generated by "stringer -type token -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

const _token_name = "EOFnameliteralopop=opop=:=<-*([{)]},;:....breakcaseclasschanconstcontinuedefaultdeferelseextendsfallthroughforwhilefuncgogotoifimportinterfaceimplementsmappackagerangereturnselectsliceofstructswitchtypevar"

var _token_index = [...]uint8{0, 3, 7, 14, 16, 19, 23, 24, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 47, 51, 56, 60, 65, 73, 80, 85, 89, 96, 107, 110, 115, 119, 121, 125, 127, 133, 142, 152, 155, 162, 167, 173, 179, 186, 192, 198, 202, 205, 205}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
