go install -i cmd/compile
go install -i cmd/go
go install -i cmd/addr2line 
go install -i cmd/api 
go install -i cmd/asm 
go install -i cmd/buildid
go install -i cmd/cgo
go install -i cmd/cover
go install -i cmd/dist
go install -i cmd/doc
go install -i cmd/fix
go install -i cmd/gofmt
go install -i cmd/link
go install -i cmd/nm
go install -i cmd/objdump
go install -i cmd/pack
go install -i cmd/pprof
go install -i cmd/test2json
go install -i cmd/trace
go install -i cmd/vet

